# Generated by Django 3.0.3 on 2020-03-16 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='family_name')),
            ],
        ),
        migrations.CreateModel(
            name='genus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='genus_name')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.family', verbose_name='genus_family')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='product_name')),
                ('amount', models.IntegerField(verbose_name='product_amount')),
                ('product_num', models.CharField(max_length=200, verbose_name='product_num')),
                ('stock_status', models.CharField(choices=[('n', 'none'), ('l', 'less then 5'), ('s', 'sufficient')], max_length=1, verbose_name='product_stock_status')),
                ('memo', models.TextField(verbose_name='product_memo')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.category')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.family')),
                ('genus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.genus')),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='supplier_name')),
                ('phone', models.CharField(max_length=200, verbose_name='supplier_phone')),
                ('address', models.CharField(max_length=200, verbose_name='supplier_address')),
                ('email', models.EmailField(max_length=200, verbose_name='supplier_email')),
            ],
        ),
        migrations.CreateModel(
            name='sold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='sold_amount')),
                ('sold_date', models.DateField(verbose_name='sold_date')),
                ('revenue', models.IntegerField(verbose_name='sold_revenue')),
                ('distribute', models.CharField(choices=[('r', 'retailer'), ('s', 'shapee')], max_length=1, verbose_name='sold_distribute')),
                ('reason', models.CharField(choices=[('s', 'sold'), ('r', 'return'), ('b', 'broken')], max_length=1, verbose_name='sold_reason')),
                ('memo', models.TextField(verbose_name='sold_memo')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.product')),
            ],
        ),
        migrations.CreateModel(
            name='pruchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volume', models.IntegerField(verbose_name='pruchase_volume')),
                ('purchase_date', models.DateField(verbose_name='purchase_date')),
                ('expenses', models.IntegerField(verbose_name='purchase_expenses')),
                ('reason', models.CharField(choices=[('s', 'sold'), ('r', 'return'), ('b', 'broken')], max_length=1, verbose_name='pruchase_reason')),
                ('memo', models.TextField(verbose_name='pruchase_memo')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.product')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.supplier'),
        ),
        migrations.AddField(
            model_name='category',
            name='suppliers',
            field=models.ManyToManyField(to='StockSystem.supplier'),
        ),
    ]
