# Generated by Django 3.0.3 on 2020-03-17 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='suppliers',
        ),
        migrations.RemoveField(
            model_name='genus',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='family_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='genus_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='pruchase',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='pruchase',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='pruchase',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='product_id',
        ),
        migrations.AddField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AddField(
            model_name='product',
            name='genus',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Genus'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AddField(
            model_name='pruchase',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AddField(
            model_name='pruchase',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Product'),
        ),
        migrations.AddField(
            model_name='pruchase',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AddField(
            model_name='sold',
            name='fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sold',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Product'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='categorys',
            field=models.ManyToManyField(blank=True, default=None, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='product_amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memo',
            field=models.TextField(blank=True, default=None, verbose_name='product_memo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_num',
            field=models.SlugField(max_length=200, unique=True, verbose_name='product_num'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('n', 'none'), ('l', 'less then 5'), ('s', 'sufficient')], default=None, max_length=1, verbose_name='product_stock_status'),
        ),
        migrations.AlterField(
            model_name='pruchase',
            name='memo',
            field=models.TextField(blank=True, default=None, verbose_name='pruchase_memo'),
        ),
        migrations.AlterField(
            model_name='pruchase',
            name='purchase_date',
            field=models.DateField(blank=True, default=None, verbose_name='purchase_date'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='memo',
            field=models.TextField(blank=True, default=None, verbose_name='sold_memo'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='sold_date',
            field=models.DateField(blank=True, default=None, verbose_name='sold_date'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='supplier_address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=200, verbose_name='supplier_email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='supplier_phone'),
        ),
    ]
