# Generated by Django 3.0.3 on 2020-03-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0007_auto_20200320_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volume', models.IntegerField(verbose_name='pruchase_volume')),
                ('purchase_date', models.DateField(blank=True, default=None, null=True, verbose_name='purchase_date')),
                ('expenses', models.IntegerField(verbose_name='purchase_expenses')),
                ('reason', models.CharField(blank=True, choices=[('s', 'sold'), ('r', 'return'), ('b', 'broken'), ('p', 'pruchase')], default='p', max_length=1, null=True, verbose_name='pruchase_reason')),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='pruchase_memo')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Genus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='distribute',
            field=models.CharField(blank=True, choices=[('r', 'retailer'), ('s', 'shapee')], default=None, max_length=1, null=True, verbose_name='sold_distribute'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='memo',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='sold_memo'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='reason',
            field=models.CharField(blank=True, choices=[('s', 'sold'), ('r', 'return'), ('b', 'broken'), ('p', 'pruchase')], default='s', max_length=1, null=True, verbose_name='sold_reason'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categorys',
            field=models.ManyToManyField(blank=True, default=None, to='StockSystem.Category'),
        ),
        migrations.DeleteModel(
            name='pruchase',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
    ]
