# Generated by Django 3.0.3 on 2020-03-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0025_auto_20200323_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_num',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='purchase_num'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Genus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='memo',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='purchase_memo'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='reason',
            field=models.CharField(blank=True, choices=[('s', 'sold'), ('r', 'return'), ('b', 'broken'), ('p', 'pruchase')], default='p', max_length=1, null=True, verbose_name='purchase_reason'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categorys',
            field=models.ManyToManyField(blank=True, default=None, to='StockSystem.Category'),
        ),
    ]
