# Generated by Django 3.0.3 on 2020-03-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0050_auto_20200324_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='product_estimated_price'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Genus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='reason',
            field=models.CharField(blank=True, choices=[('s', 'sold'), ('d', 'discount'), ('r', 'return'), ('b', 'broken'), ('p', 'pruchase')], default='p', max_length=1, null=True, verbose_name='purchase_reason'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='reason',
            field=models.CharField(blank=True, choices=[('s', 'sold'), ('d', 'discount'), ('r', 'return'), ('b', 'broken'), ('p', 'pruchase')], default='s', max_length=1, null=True, verbose_name='sold_reason'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categorys',
            field=models.ManyToManyField(blank=True, default=None, to='StockSystem.Category'),
        ),
    ]
