# Generated by Django 3.0.3 on 2020-03-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0067_auto_20200331_0725'),
    ]

    operations = [
        #migrations.RemoveField('Sold_Nun', 'get_total_cost'),
        #migrations.RemoveField('Purchase_NUm', 'get_total_cost'),
        migrations.RemoveField('Purchase', 'purchase_num'),
        migrations.RemoveField('Sold', 'sold_num'),
        migrations.RenameModel('Sold_Nun', 'SoldNum'), 
        migrations.RenameModel('Purchase_Num', 'PurchaseNum'),
        

    ]
