# Generated by Django 3.0.3 on 2020-04-08 05:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0079_auto_20200405_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasenum',
            old_name='purchase_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='soldnum',
            old_name='sold_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 4, 8)),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 5, 35, 55, 808180)),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 4, 8)),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 5, 35, 55, 809917)),
        ),
        migrations.AddField(
            model_name='purchasenum',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 5, 35, 55, 809636)),
        ),
        migrations.AddField(
            model_name='sold',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 4, 8)),
        ),
        migrations.AddField(
            model_name='sold',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 5, 35, 55, 809230)),
        ),
        migrations.AddField(
            model_name='soldnum',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 5, 35, 55, 808877)),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateField(default=datetime.date(2020, 4, 8)),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 5, 35, 55, 806714)),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Genus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categorys',
            field=models.ManyToManyField(blank=True, default=None, to='StockSystem.Category'),
        ),
    ]
