# Generated by Django 3.0.3 on 2020-04-15 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0088_auto_20200411_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Genus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='plant_size',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, 'other')], default=0, null=True, verbose_name='product_plant_size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categorys',
            field=models.ManyToManyField(blank=True, default=None, to='StockSystem.Category'),
        ),
    ]
