# Generated by Django 3.0.3 on 2020-04-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0092_auto_20200415_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchasenum',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='soldnum',
            name='checkout',
        ),
        migrations.AddField(
            model_name='purchasenum',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AddField(
            model_name='purchasenum',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='total_cost'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Genus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='StockSystem.Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='StockSystem.Product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='categorys',
            field=models.ManyToManyField(blank=True, default=None, to='StockSystem.Category'),
        ),
    ]
